name: Build images
on:
  push:
    branches:
      - master
jobs:
  ros2-devel-focal:
    # ubuntu-latest is too old (ubuntu-latest == ubuntu-18.04)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ros2/focal/
          repository: christophebedard/images
          tags: ros2-devel-focal
          labels: ade_image_commit_sha=${{ github.sha }}
          add_git_labels: true
