name: Build images

on:
  push:
    branches:
      - master
    # paths:
    #   - 'powerline-shell/**'

jobs:
  build_images:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {DIR: powerline-shell, REPO: christophebedard/images, TAG: powerline-shell}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build images
        env: ${{matrix.env}}
        run: |
          cd $DIR
          make prep
      - uses: docker/build-push-action@v1
        env: ${{matrix.env}}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: $REPO
          tags: $TAG
